// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyrvjsbeowurihgjyuhx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95cnZqc2Jlb3d1cmloZ2p5dWh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNDA1MTUsImV4cCI6MjA1OTkxNjUxNX0.BLZd_tqyrq_q94wSkD1NXG0Z02X3IY4Dwh0NgAjW8_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);